### PR TITLE
fix: Support default CR starting with dashes

### LINKED ISSUE #143: Check if we parse yamls correctly
**Description**

This is likely an error with old CLI, but we should check if we have the same issue with modulectl.

Telemetry created a ModuleTempalte where default CR starts with `---`, see: https://github.tools.sap/kyma/module-manifests/blob/9012a3d1325e1f21dc8a0fcf94b903bb35fc9e3f/modules/telemetry/experimental/telemetry-default-cr.yaml#L1

```yaml
---
apiVersion: operator.kyma-project.io/v1alpha1
kind: Telemetry
metadata:
  labels:
    app.kubernetes.io/name: telemetry
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: telemetry-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-manager
  name: default
```

This was copied as is into the ModuleTempalte, see: https://github.tools.sap/kyma/kyma-modules/blob/7e5a2eae968a238eaf57f41a1b263dc43425d0c9/experimental/moduletemplate-telemetry.yaml#L16

```yaml
apiVersion: operator.kyma-project.io/v1beta2
kind: ModuleTemplate
metadata:
  name: telemetry-experimental
  namespace: kcp-system
  labels:
    "operator.kyma-project.io/module-name": "telemetry"
  annotations:
    "operator.kyma-project.io/doc-url": "https://help.sap.com/docs/btp/sap-business-technology-platform/kyma-telemetry-module"
    "operator.kyma-project.io/is-cluster-scoped": "false"
    "operator.kyma-project.io/module-version": "1.32.0-experimental" 
spec:
  channel: experimental
  mandatory: false 
  data:
    ---
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Telemetry
    metadata:
      labels:
        app.kubernetes.io/name: telemetry
        app.kubernetes.io/instance: default
        app.kubernetes.io/part-of: telemetry-manager
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/created-by: telemetry-manager
      name: default
    
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/module/telemetry
// ...
```

**Expected result**

ModuleTemplate shall not have yaml separators `---`

**Actual result**

ModuleTemplate has yaml separators `---`

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by nesmabadr**
**Description**

Changes proposed in this pull request:

- Support Default CR starting with dashes
- Add unit test for this case

**Related issue(s)**
Resolves #143

### CODE REVIEW

File: internal/service/templategenerator/templategenerator_test.go [hunk 1]
```diff
@@ -62,7 +68,6 @@ func TestGenerateModuleTemplate_Success(t *testing.T) {
 	require.Contains(t, mockFS.writtenTemplate, "moduleName: component")
 	require.Contains(t, mockFS.writtenTemplate, "component-1.0.0")
 	require.Contains(t, mockFS.writtenTemplate, "default")
-	require.Contains(t, mockFS.writtenTemplate, "test-data")
```
Comment (c-pius) [inline internal/service/templategenerator/templategenerator_test.go:65]: Can we use a check like contains `kind: Sample` to still verify this is written?

File: internal/service/templategenerator/templategenerator_test.go [hunk 2]
```diff
@@ -71,6 +76,52 @@ func TestGenerateModuleTemplate_Success(t *testing.T) {
...
+	require.Contains(t, mockFS.writtenTemplate, "default")
+	require.Contains(t, mockFS.writtenTemplate, "example.com/component")
+	require.Contains(t, mockFS.writtenTemplate, "someResource")
+	require.Contains(t, mockFS.writtenTemplate, "https://some.other/location/template-operator.yaml")
+	require.Contains(t, mockFS.writtenTemplate, "rawManifest")
+	require.Contains(t, mockFS.writtenTemplate,
+		"https://github.com/kyma-project/template-operator/releases/download/1.0.1/template-operator.yaml")
+	require.NotContains(t, mockFS.writtenTemplate, "---")
+	require.Contains(t, mockFS.writtenTemplate, "apiVersion: operator.kyma-project.io/v1alpha1")
+	require.Contains(t, mockFS.writtenTemplate, "kind: Sample")
```
Comment (c-pius) [inline internal/service/templategenerator/templategenerator_test.go:118]: Here I see we do :)

**Review by c-pius — APPROVED** [review]
Consider it approved with suggestion :) The change looks good, one suggestion would be if we could consider streamlining the test cases (only if time allows and you feel like doing it)...

It looks as if we have a set of very similar tests where each is having a shared core (the minimal information that is put into the module template) and each test adding a small part on top (e.g., when associated resources are present, when downtime is set, ...) Would it be possible to use the pattern with an array of test cases where we pass assert functions to the test case? We could have one assert function that is used by all tests verifying the common part, and then pass one function that verifies the specific addition by this test. This would make it easier to see the common part, the individual changes by each test, and make it more robust if things change in the common part in the future.

**Review by c-pius — APPROVED** [review]
Nice!
