### PR TITLE
fix: Update ModuleTemplate's Metadata name

### LINKED ISSUE #62: [ModuleCatalog] ModuleTemplate's `metadata.name` is `<module-name>-<version>`
## Description

Use the `module-config.yaml`'s `version` instead of the `channel` to generate the ModuleTemplate's `.metadata.name` attribute.

## Reason

New module templates will follow a new naming schema. See https://github.com/kyma-project/lifecycle-manager/issues/1681 section "Requirements for ModuleTemplates".

## AC

- [x] given a module config like
  ```yaml
  name: kyma-project.io/module/template-operator
  version: 1.0.0
  ```
- [x] the generate module template should look like
  ```yaml
  metadata:
    name: template-operator-1.0.0
  ```
- [x] Adapt E2E tests to cover new naming scheme
- [x] Clarify process of handover and note it down in https://github.com/orgs/kyma-project/projects/30/views/13?pane=issue&itemId=83269799

### PR DESCRIPTION
**Pull request by amritanshusikdar**
**Related issue(s)**
Resolves #62

### CODE REVIEW

**Comment by nesmabadr** [comment]
The handover process is not yet defined for the change of ModuleTemplate name

File: tests/e2e/create/create_test.go [hunk 1]
```diff
@@ -218,6 +219,10 @@ var _ = Describe("Test 'create' command", Ordered, func() {
 			Expect(descriptor).ToNot(BeNil())
 			Expect(descriptor.SchemaVersion()).To(Equal(v2.SchemaVersion))
 
+			descriptorSplit := strings.Split(descriptor.Name, "/")
+			descriptorName := descriptorSplit[len(descriptorSplit)-1]
+			Expect(template.Name).To(Equal(descriptorName + "-" + descriptor.Version))
```
Comment (nesmabadr) [inline tests/e2e/create/create_test.go:224]:
```suggestion
			Expect(template.Name).To(Equal("template-operator-1.0.0"))
```

Comment (nesmabadr) [reply tests/e2e/create/create_test.go:224]: There is no need to get the name from the descriptor. Also can you add this line to some of the tests below as well?

**Review by nesmabadr — APPROVED** [review]
